### PR TITLE
Refused packet makes go_ora panicking

### PR DESCRIPTION
**Pull request by simulot**
Company's security rules block direct connection to oracle server when the VPN is on. 

The connect packet is refused, and the actual refused packet is 12 bytes long. This cause a panic in function `newRefusePacketFromData` when trying to get message beyond the 12th byte.

```
panic: runtime error: slice bounds out of range [:383] with capacity 16

goroutine 1 [running]:
github.com/sijms/go-ora/network.newRefusePacketFromData(0xc000012100, 0xc, 0x10, 0xc)
        C:/Users/me/go/src/github.com/sijms/go-ora/network/refuse_packet.go:44 +0x165
github.com/sijms/go-ora/network.(*Session).readPacket(0xc0000021e0, 0x0, 0x0, 0x0, 0xfd)
        C:/Users/me/go/src/github.com/sijms/go-ora/network/session.go:270 +0x10c
github.com/sijms/go-ora/network.(*Session).Connect(0xc0000021e0, 0xc0000021e0, 0x203000000000000)
        C:/Users/me/go/src/github.com/sijms/go-ora/network/session.go:76 +0x2a9
github.com/sijms/go-ora.(*Connection).Open(0xc000048000, 0x18, 0x0)
        C:/Users/me/go/src/github.com/sijms/go-ora/connection.go:232 +0x1a5
main.main()
        C:/Users/me/go/src/github.com/sijms/go-ora/examples/hello_ora/main.go:35 +0x10a
```
Here is a fix for not panicking and return an error.

I have added `hello_ora` program to test connection. I have put it into the subfolder `examples/hello_ora`.

```
hello_ora
        hello_ora check if it can connect to the given oracle server, then print server banner.

Usage:
        hello_ora oracle://user:pass@server/service_name

```

On successful connection:

```
go run . 'oracle://user:pass@server/service_name'

Successfully connected.

Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
PL/SQL Release 11.2.0.2.0 - Production
CORE    11.2.0.2.0      Production
TNS for Linux: Version 11.2.0.2.0 - Production
NLSRTL Version 11.2.0.2.0 - Production

```

On refused connection:
```
go run . 'oracle://user:pass@server/service_name'
Can't open connection: connection refused by the server
```

### CODE REVIEW

**Comment by sijms** [comment]
yes actually I didn't implement refuse package 
thank you

**Comment by sijms** [comment]
now I need to fix redirect_packet also. but I cannot receive one to analyze
did you receive redirect packet before

**Comment by simulot** [comment]
When the VPN is on, I can't connect to a server on my local lan. What an intrusive VPN/FW!

Then the response to ConnectPacket is 0,12,0,0,4,0,0,0,1,114 
I don't know the is packet is longer. The func readPacketData stops at the 12th byte, as indicated in the first word of the buffer.

Otherwise, when not connected to the vpn, the response to Connect is Accept and then Data. 

May be I can configure my local server to get a Redirect, but how?

**Comment by sijms** [comment]
according to #23 they are using RAC to get redirect packet

**Comment by sijms** [comment]
I think reconnect data is send in DataPacket after RedirectPacket

**Pull request merged**
