### PR TITLE
Serious NUMBER testing and refactoring EncodeDouble

### PR DESCRIPTION
**Pull request by simulot**
I have found some random errors during my tests. 

To ease the test of plenty of floats, I have build a system to put oracle binary representation automatically in a test functions. The program queries an oracle server and build following structure with results. See  `go-ora\converters\generatefloat\main.go`

``` go
var testFloatVualue = []struct {
	SelectText string
	OracleText string
	Float      float64
	Binary     []byte
}{
	{"0", "0", 0, []byte{128}},                                                                      // 0.000000e+00
	{"1", "1", 1, []byte{193, 2}},                                                                   // 1.000000e+00
	{"10", "10", 10, []byte{193, 11}},                                                               // 1.000000e+01
	{"100", "100", 100, []byte{194, 2}},                                                             // 1.000000e+02
	{"1000", "1000", 1000, []byte{194, 11}},                                                         // 1.000000e+03
	{"10000000", "10000000", 1e+07, []byte{196, 11}},                                                // 1.000000e+07
	{"1E+30", "1000000000000000000000000000000", 1e+30, []byte{208, 2}},                             // 1.000000e+30
	{"1E+125", "1.000000000000000000000000000000000E+125", 1e+125, []byte{255, 11}},                 // 1.000000e+125
	{"0.1", ".1", 0.1, []byte{192, 11}},                                                             // 1.000000e-01
	{"0.01", ".01", 0.01, []byte{192, 2}},                                                           // 1.000000e-02
	{"0.001", ".001", 0.001, []byte{191, 11}},                                                       // 1.000000e-03
...

```
Then I have adapted test functions to check encode / decode function to use it. I have found many errors in DecodeDouble, but none on DecodeDouble2. 
The reason I still got errors after the merge of PR is that `func (stmt *Stmt) read(dataSet *DataSet) error` call DoubleDecode instead of DoubleDecode2.
https://github.com/sijms/go-ora/blob/451cdd0f12dcaedc96ba1a4f71e09d43aaee8238/command.go#L551-L561

I ran new test on DecodeDouble:
```
Running tool: C:\Go\bin\go.exe test -timeout 30s github.com\sijms\go-ora\converters -run ^TestDecodeDouble$

--- FAIL: TestDecodeDouble (0.00s)
    --- FAIL: TestDecodeDouble/1.234 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 1.234e+08, want 1.234, Error= 1.234000e+08
    --- FAIL: TestDecodeDouble/123.4 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 1.234e+06, want 123.4, Error= 1.233877e+06
    --- FAIL: TestDecodeDouble/0.01234 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 1.234e+10, want 0.01234, Error= 1.234000e+10
    --- FAIL: TestDecodeDouble/0.0001234 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 1.234e+12, want 0.0001234, Error= 1.234000e+12
    --- FAIL: TestDecodeDouble/0.000001234 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 1.234e+14, want 1.234e-06, Error= 1.234000e+14
    --- FAIL: TestDecodeDouble/-1.234 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -1.234e+08, want -1.234, Error= 1.234000e+08
    --- FAIL: TestDecodeDouble/-123.4 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -1.234e+06, want -123.4, Error= 1.233877e+06
    --- FAIL: TestDecodeDouble/-1.234#01 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -1.234e+08, want -1.234, Error= 1.234000e+08
    --- FAIL: TestDecodeDouble/-123.4#01 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -1.234e+06, want -123.4, Error= 1.233877e+06
    --- FAIL: TestDecodeDouble/9.8765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+08, want 9.8765, Error= 9.876500e+08
    --- FAIL: TestDecodeDouble/98.765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+09, want 98.765, Error= 9.876500e+09
    --- FAIL: TestDecodeDouble/987.65 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+06, want 987.65, Error= 9.875512e+06
    --- FAIL: TestDecodeDouble/9876.5 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+07, want 9876.5, Error= 9.875512e+07
    --- FAIL: TestDecodeDouble/0.98765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+11, want 0.98765, Error= 9.876500e+11
    --- FAIL: TestDecodeDouble/0.098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+10, want 0.098765, Error= 9.876500e+10
    --- FAIL: TestDecodeDouble/0.0098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+13, want 0.0098765, Error= 9.876500e+13
    --- FAIL: TestDecodeDouble/0.00098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+12, want 0.00098765, Error= 9.876500e+12
    --- FAIL: TestDecodeDouble/0.000098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+15, want 9.8765e-05, Error= 9.876500e+15
    --- FAIL: TestDecodeDouble/0.0000098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+14, want 9.8765e-06, Error= 9.876500e+14
    --- FAIL: TestDecodeDouble/0.00000098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 9.8765e+17, want 9.8765e-07, Error= 9.876500e+17
    --- FAIL: TestDecodeDouble/-9.8765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+08, want -9.8765, Error= 9.876500e+08
    --- FAIL: TestDecodeDouble/-98.765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+09, want -98.765, Error= 9.876500e+09
    --- FAIL: TestDecodeDouble/-987.65 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+06, want -987.65, Error= 9.875512e+06
    --- FAIL: TestDecodeDouble/-9876.5 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+07, want -9876.5, Error= 9.875512e+07
    --- FAIL: TestDecodeDouble/-0.98765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+11, want -0.98765, Error= 9.876500e+11
    --- FAIL: TestDecodeDouble/-0.098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+10, want -0.098765, Error= 9.876500e+10
    --- FAIL: TestDecodeDouble/-0.0098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+13, want -0.0098765, Error= 9.876500e+13
    --- FAIL: TestDecodeDouble/-0.00098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+12, want -0.00098765, Error= 9.876500e+12
    --- FAIL: TestDecodeDouble/-0.000098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+15, want -9.8765e-05, Error= 9.876500e+15
    --- FAIL: TestDecodeDouble/-0.0000098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+14, want -9.8765e-06, Error= 9.876500e+14
    --- FAIL: TestDecodeDouble/-0.00000098765 (0.00s)
        type_conversion_test.go:51: DecodeDouble() = -9.8765e+17, want -9.8765e-07, Error= 9.876500e+17
    --- FAIL: TestDecodeDouble/2*asin(1) (0.00s)
        type_conversion_test.go:51: DecodeDouble() = 3.14159265358979, want 3.141592653589793, Error= 3.108624e-15
FAIL
FAIL	github.com/sijms/go-ora/converters	0.283s
FAIL
```

Function DoubleDecode2 pass the same test:
```
Running tool: C:\Go\bin\go.exe test -timeout 30s github.com\sijms\go-ora\converters -run ^TestEncodeDouble2$

ok  	github.com/sijms/go-ora/converters	0.314s

```

Now, I have acquired a good knowledge on how NUMBERS are encoded, I undertook to rewrite DoubleEncoding to add readability and maintainability to the code. The new code is a lot simpler that don't use any table of number nor successive float operations:

``` go
func EncodeDouble2(num float64) ([]byte, error) {
	if num == 0.0 {
		return []byte{128}, nil
	}

	var (
		err      error
		negative bool
		exponent int
		mantissa int
	)

	// Let's the standard library doing the delicate work of converting binary float to decimal figures
	s := []byte(strconv.FormatFloat(num, 'e', -1, 64))

	if s[0] == '-' {
		negative = true
		s = s[1:]
	}

	if i := bytes.Index(s, []byte{'e'}); i >= 0 {
		exponent, err = strconv.Atoi(string(s[i+1:]))
		if err != nil {
			return nil, err
		}
		if exponent%2 != 0 {
			s = s[:i]
		} else {
			s = append([]byte("0"), s[:i]...)
		}
		if exponent < 0 {
			exponent--
		}
	}

	if i := bytes.Index(s, []byte{'.'}); i >= 0 {
		s = append(s[:i], s[i+1:]...)
	}

	mantissa = len(s)
	size := 1 + (mantissa+1)/2
	if negative && mantissa < 21 {
		size++
	}
	buf := make([]byte, size, size)

	for i := 0; i < mantissa; i += 2 {
		b := 10 * (s[i] - '0')
		if i < mantissa-1 {
			b += s[i+1] - '0'
		}
		if negative {
			b = 100 - b
		}
		buf[1+i/2] = b + 1
	}

	if negative && mantissa < 21 {
		buf[len(buf)-1] = 0x66
	}

	exponent = (exponent / 2) + 1
	if negative {
		buf[0] = byte(exponent+64) ^ 0x7f
	} else {
		buf[0] = byte(exponent+64) | 0x80
	}
	return buf, nil
}
```

### CODE REVIEW

**Comment by sijms** [comment]
I will use your function DecodeDouble2
but are you test EncodeDouble2 by sending parameter to oracle and see if it represented well?

**Comment by simulot** [comment]
Not yet. 
I'm progressing in this way.

I'm also refactoring DecodeInt and EncodeInt

**Comment by sijms** [comment]
ok thanks a lot for your effort

**Comment by simulot** [comment]
You're welcome.

**Pull request merged**
