### PR TITLE
fix: longer lob allowed now. ( > MAX_LEN_VARCHAR2)

### PR DESCRIPTION
**Pull request by uonun**
- for go_ora.NClob parameters, lob.read() will not return EOF now.

### CODE REVIEW

**Comment by uonun** [comment]
Thank you again for fixing this issue: https://github.com/sijms/go-ora/issues/260
but i found a bug that, when the go_ora.NClob is longer than 4000, there is an error "EOF" returnd.
after the 2 lines assigning the size of lob are commented, it works well.

pls have a look.

**Comment by sijms** [comment]
ok I will test it first

**Comment by sijms** [comment]
I fix the problem in this release
you can find the code in [here](https://github.com/sijms/go-ora/blob/master/examples/nclob/main.go)

**Comment by uonun** [comment]
v2.5.8 updated, still does not work...

tested value:
```
value := "😁🍎🇨🇳㊣①❷㏾罗🀄︎🌈🔥"
// make sure more than 4k bytes.
value = strings.Repeat(value, 100)
// ...
db.Exec(`INSERT INTO TABLE (customer_id,address) VALUES (1,:1) RETURNING customer_id INTO :2`, go_ora.NClob{String: value, Valid: true}, &newid)
```

image

image

**Comment by sijms** [comment]
this is the code you request
```golang
package main

import (
	"database/sql"
	"flag"
	"fmt"
	go_ora "github.com/sijms/go-ora/v2"
	"os"
	"strings"
	"time"
)

var buffer2 = strings.Repeat("😁🍎🇨🇳㊣①❷㏾罗🀄︎🌈🔥", 100)

func createTable(conn *sql.DB) error {
	t := time.Now()
	sqlText := `CREATE TABLE GOORA_TEMP_VISIT(
	VISIT_ID	number(10)	NOT NULL,
	VISIT_DATA  NCLOB
	)`
	_, err := conn.Exec(sqlText)
	if err != nil {
		return err
	}
	fmt.Println("Finish create table GOORA_TEMP_VISIT :", time.Now().Sub(t))
	return nil
}

func dropTable(conn *sql.DB) error {
	t := time.Now()
	_, err := conn.Exec("drop table GOORA_TEMP_VISIT purge")
	if err != nil {
		return err
	}
	fmt.Println("Finish drop table: ", time.Now().Sub(t))
	return nil
}

func insertData(conn *sql.DB) error {
	t := time.Now()
	//val, err := ioutil.ReadFile("clob.json")
	//if err != nil {
	//	return err
	//}
	var visitID int64
	_, err := conn.Exec(`INSERT INTO GOORA_TEMP_VISIT(VISIT_ID, VISIT_DATA) VALUES(1, :1) returning visit_id into :2`, go_ora.NClob{String: buffer2}, &visitID)
	if err != nil {
		return err
	}
	fmt.Println("1 row inserted: ", time.Now().Sub(t), "\tID: ", visitID)
	return nil
}

func readWithSql(conn *sql.DB) error {
	t := time.Now()
	var (
		visitID   int64
		visitData go_ora.NVarChar
	)
	err := conn.QueryRow(`SELECT VISIT_ID, VISIT_DATA FROM GOORA_TEMP_VISIT`).Scan(&visitID, &visitData)
	if err != nil {
		return err
	}
	printLargeString("Data: ", string(visitData))
	fmt.Println("1 row read by sql: ", time.Now().Sub(t))
	return nil
}
func readWithOutPutPars(conn *sql.DB) error {
	t := time.Now()
	sqlText := `BEGIN
SELECT VISIT_DATA INTO :1 FROM GOORA_TEMP_VISIT WHERE VISIT_ID = 1;
END;`
	var data go_ora.NClob
	_, err := conn.Exec(sqlText, go_ora.Out{Dest: &data, Size: 100000})
	if err != nil {
		return err
	}
	printLargeString("Data: ", data.String)
	fmt.Println("1 row read by output parameters: ", time.Now().Sub(t))
	return nil
}
func printLargeString(prefix, data string) {
	if len(data) <= 25 {
		fmt.Println(prefix, data)
		return
	}
	temp := strings.ReplaceAll(data, "\r", "")
	temp = strings.ReplaceAll(temp, "\n", "\\n")
	fmt.Println(prefix, temp[:25], "...........", temp[len(temp)-25:], "\tsize: ", len(data))
}
func usage() {
	fmt.Println()
	fmt.Println("nclob")
	fmt.Println("  a code for using NClob by create table GOORA_TEMP_VISIT then insert then drop")
	fmt.Println()
	fmt.Println("Usage:")
	fmt.Println(`  nclob -server server_url`)
	flag.PrintDefaults()
	fmt.Println()
	fmt.Println("Example:")
	fmt.Println(`  nclob -server "oracle://user:pass@server/service_name"`)
	fmt.Println()
}
func main() {
	var server string
	flag.StringVar(&server, "server", "", "Server's URL, oracle://user:pass@server/service_name")
	flag.Parse()

	connStr := os.ExpandEnv(server)
	if connStr == "" {
		fmt.Println("Missing -server option")
		usage()
		os.Exit(1)
	}
	fmt.Println("Connection string: ", connStr)

	conn, err := sql.Open("oracle", connStr)
	if err != nil {
		fmt.Println("Can't open the driver", err)
		return
	}

	defer func() {
		err = conn.Close()
		if err != nil {
			fmt.Println("Can't close connection", err)
		}
	}()

	err = conn.Ping()
	if err != nil {
		fmt.Println("Can't ping connection", err)
		return
	}

	err = createTable(conn)
	if err != nil {
		fmt.Println("Can't create table", err)
		return
	}
	defer func() {
		err = dropTable(conn)
		if err != nil {
			fmt.Println("Can't drop table", err)
		}
	}()

	err = insertData(conn)
	if err != nil {
		fmt.Println("Can't insert data: ", err)
		return
	}

	err = readWithSql(conn)
	if err != nil {
		fmt.Println("Can't read data with sql: ", err)
		return
	}

	err = readWithOutPutPars(conn)
	if err != nil {
		fmt.Println("Can't read data with output parameter: ", err)
		return
	}
}
```

the result:
```
Finish create table GOORA_TEMP_VISIT : 134.70726ms
1 row inserted:  724.052579ms   ID:  1
Data:  😁🍎🇨🇳㊣①❷ ........... �❷㏾罗🀄︎🌈🔥   size:  4600
1 row read by sql:  104.526374ms
Data:  😁🍎🇨🇳㊣①❷ ........... �❷㏾罗🀄︎🌈🔥   size:  4600
1 row read by output parameters:  16.12184ms
Finish drop table:  1.086523468s
```

would you run this code and see if you get same results

**Comment by uonun** [comment]
if 
```
	// lob.size = int64(len([]rune(data)))
	// lob.sendSize = true
```
then, yes:
```
Finish create table GOORA_TEMP_VISIT : 7.097829ms
1 row inserted:  16.896469ms    ID:  1
Data:  😁🍎🇨🇳㊣①❷ ........... �❷㏾罗🀄︎🌈🔥      size:  4600
1 row read by sql:  3.288541ms
Data:  😁🍎🇨🇳㊣①❷ ........... �❷㏾罗🀄︎🌈🔥      size:  4600
1 row read by output parameters:  4.450612ms
Finish drop table:  22.41028ms
```

otherwise, no:
```
Finish create table GOORA_TEMP_VISIT : 23.419615ms
Can't insert data:  EOF
Can't drop table EOF
```

**Comment by sijms** [comment]
I run it without comment these lines
can you tell me what is your oracle server version?

**Comment by sijms** [comment]
yes now I get the error when run the code on oracle 11g

**Pull request merged**
